apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-odp-cron-operator.name" . }}
  labels:
{{- include "eric-odp-cron-operator.labels" . | indent 4 }}
  annotations:
{{- include "eric-odp-cron-operator.annotations-with-prometheus" . | nindent 4 }}
data:
  LOG_CTRL_FILE: |-
{{ .Files.Get "logcontrol.json" | indent 4}}
